### ISSUE TITLE
请问由商品序列生成graph的时候，这里是不是生成的有向图

### ISSUE THREAD

**Issue by zouxiaokun** [wangzhegeek/EGES#10]
# session2graph
    node_pair = dict()
    for session in session_list_all:
        for i in range(1, len(session)):
            if (session[i - 1], session[i]) not in node_pair.keys():
                node_pair[(session[i - 1], session[i])] = 1
            else:
                node_pair[(session[i - 1], session[i])] += 1

    in_node_list = list(map(lambda x: x[0], list(node_pair.keys())))
    out_node_list = list(map(lambda x: x[1], list(node_pair.keys())))
    weight_list = list(node_pair.values())
    graph_df = pd.DataFrame({'in_node': in_node_list, 'out_node': out_node_list, 'weight': weight_list})

**Comment by wangzhegeek** [comment]
是的

**Comment by zouxiaokun** [comment]
> 
> 
> 是的

谢谢

**Comment by zouxiaokun** [comment]
> 
> 
> 是的

请问是不是将
walker.preprocess_transition_probs()   # long time and oom
这一句删除并企鹅修改pq为1就可以做deepwalk了呢？
node2vec好像有一点吃不消。哈哈哈

**Comment by wangzhegeek** [comment]
游走的方法并不唯一，可以根据自己的需求改的简单点
