### ISSUE TITLE
groupby('user_id').agg(list)报错

### ISSUE THREAD

**Issue by phoenixzxj** [wangzhegeek/EGES#12]
ValueError: no results

**Comment by ChunyuanXu** [comment]
I meet a problem in the same line. That is, ValueError: No objects to concatenate.
It seems to be the problem of the pandas version.
So I use the code below to replace the orginal code. It works!
------
group_action_data = action_data.groupby('user_id').agg(pd.Series.tolist)
session_list = group_action_data.apply(cnt_session, axis=1)
return session_list.values
------

**Comment by wangzhegeek** [comment]
you can update your pandas and try angin.
