### ISSUE TITLE
Preprocess transition probs...这一步时间很长

### ISSUE THREAD

**Issue by JarvisFei** [wangzhegeek/EGES#15]
这一步时间非常长，而且，内存会从几个G慢慢变得越来越大，最后256G的内存会爆掉

**Comment by wangzhegeek** [comment]
节点数太多建议用deepwalk的游走，别用Node2vec

**Comment by greenary-John** [comment]
> 这一步时间非常长，而且，内存会从几个G慢慢变得越来越大，最后256G的内存会爆掉

老哥，多少节点数？
说实话我比较好奇，需要内存这么大，阿里怎么训的，他们不是上线了吗，阿里应该几亿节点了吧？
