### ISSUE TITLE
side information embedding是否被所有node共享的问题

### ISSUE THREAD

**Issue by Yu-Qing-Wang** [wangzhegeek/EGES#18]
代码中每个side information对应一个embedding层：
```
def embedding_init(self):
    cat_embedding_vars = []
    for i in range(self.num_feat):
        embedding_var = tf.Variable(tf.random_uniform((self.feature_lens[i], self.embedding_dim), -1, 1), name='embedding'+str(i),
                                        trainable=True)
        cat_embedding_vars.append(embedding_var)
    return cat_embedding_vars
```
这样生成的所有的side information的embedding lookup table的尺寸为：
**（side information个数，side information的取值个数（不固定），embedding向量维度）**

但是论文中2.4节第三段提到对于每个node的每个side information，都有其单独对应的一个embedding向量：
> Specifically, W_v_0 denotes the embedding of item v , and W_v_s denotes the embedding of the s-th type of side information attached to item v. 

意思是不是所有的side information的embedding lookup table应该有如下尺寸：
**（node个数，side information个数，side information的取值个数（不固定），embedding向量维度）**？这样若两个node的同一个side information的取值相同，这两个side information的embedding也会不一样。但是按照代码里的逻辑，它们的embedding是一样的。

**Comment by anmingyu11** [comment]
@Yu-Qing-Wang 我也在怀疑这个问题，如果按照这个实现不就是一堆不同尺寸的embedding矩阵然后训练了一下么？还跟side_information有什么关系？

**Comment by anmingyu11** [comment]
@Yu-Qing-Wang 能加个微信么，我现在在复现这个论文，有些问题想请教一下。

**Comment by Yu-Qing-Wang** [comment]
@anmingyu11 发你qq邮箱了。

**Comment by wangzhegeek** [comment]
> 代码中每个side information对应一个embedding层：
> 
> ```
> def embedding_init(self):
>     cat_embedding_vars = []
>     for i in range(self.num_feat):
>         embedding_var = tf.Variable(tf.random_uniform((self.feature_lens[i], self.embedding_dim), -1, 1), name='embedding'+str(i),
>                                         trainable=True)
>         cat_embedding_vars.append(embedding_var)
>     return cat_embedding_vars
> ```
> 
> 这样生成的所有的side information的embedding lookup table的尺寸为：
> **（side information个数，side information的取值个数（不固定），embedding向量维度）**
> 
> 但是论文中2.4节第三段提到对于每个node的每个side information，都有其单独对应的一个embedding向量：
> 
> > Specifically, W_v_0 denotes the embedding of item v , and W_v_s denotes the embedding of the s-th type of side information attached to item v.
> 
> 意思是不是所有的side information的embedding lookup table应该有如下尺寸：
> **（node个数，side information个数，side information的取值个数（不固定），embedding向量维度）**？这样若两个node的同一个side information的取值相同，这两个side information的embedding也会不一样。但是按照代码里的逻辑，它们的embedding是一样的。

我理解若两个node的同一个side information的取值相同，这两个side information的embedding是一样的值，如果不一样的话首先参数量剧增，再一个怎么做冷启动呢？

**Comment by Fairymoon008** [comment]
两个node的同一个side information的取值相同，这两个side information的embedding是一样的值。只是他们各自对应的权重值不同。另外问下，新物品时，边的embedding的权重值如何确定。

**Comment by Yu-Qing-Wang** [comment]
> 两个node的同一个side information的取值相同，这两个side information的embedding是一样的值。只是他们各自对应的权重值不同。另外问下，新物品时，边的embedding的权重值如何确定。

新物品时，边的embedding的权重值如何确定。这个论文里确实没说，我自己的做法是用训练出来的所有node的、各side-information的权重做个平均，然后新物品统一用这个平均后的各side-information值作为权重。

**Comment by bound2020** [comment]
> > 两个node的同一个side information的取值相同，这两个side information的embedding是一样的值。只是他们各自对应的权重值不同。另外问下，新物品时，边的embedding的权重值如何确定。
> 
> 新物品时，边的embedding的权重值如何确定。这个论文里确实没说，我自己的做法是用训练出来的所有node的、各side-information的权重做个平均，然后新物品统一用这个平均后的各side-information值作为权重。

我也是这么做的

**Comment by lijinze9456yy000** [comment]
@Yu-Qing-Wang 你好，方便加一下你的微信吗，我也在复现这篇论文，谢谢~
