### ISSUE TITLE
为什么要将多个session串成一个大session？

### ISSUE THREAD

**Issue by razrLeLe** [wangzhegeek/EGES#2]
session_items = []
    for lst in session_list:
        lst = list(map(int, lst)) + [0]
        session_items.extend(lst)

在后续生成target的时候这里不会将一些原本没有共现关系的item弄成共现的了吗？

**Comment by wangzhegeek** [comment]
这个是word2vec的一种处理方式，确实不是很严谨，你也可以用其他的处理方式来做
