### ISSUE TITLE
权重矩阵如何获取到？？

### ISSUE THREAD

**Issue by Fairymoon008** [wangzhegeek/EGES#24]
我看模型文件
tensor_name:  softmax_w/Adam_1
tensor_name:  softmax_w
tensor_name:  softmax_b/Adam
tensor_name:  softmax_b
tensor_name:  embedding3/Adam_1
tensor_name:  embedding3
tensor_name:  embedding2/Adam
tensor_name:  embedding2
tensor_name:  embedding1/Adam
tensor_name:  Variable/Adam_1
tensor_name:  embedding0/Adam_1
tensor_name:  embedding0/Adam
tensor_name:  beta2_power
tensor_name:  embedding2/Adam_1
tensor_name:  embedding0
tensor_name:  softmax_w/Adam
tensor_name:  beta1_power
tensor_name:  embedding1/Adam_1
tensor_name:  embedding1
tensor_name:  embedding3/Adam
tensor_name:  Variable/Adam
tensor_name:  softmax_b/Adam_1
tensor_name:  Variable
这些哪个是权重矩阵值。embedding0,embedding1,embedding2,embedding3的值应该是sku的embedding、brand、cate和shop的embedding吧

**Comment by wangzhegeek** [comment]
是的

**Comment by zaibian** [comment]
> 我看模型文件 tensor_name: softmax_w/Adam_1 tensor_name: softmax_w tensor_name: softmax_b/Adam tensor_name: softmax_b tensor_name: embedding3/Adam_1 tensor_name: embedding3 tensor_name: embedding2/Adam tensor_name: embedding2 tensor_name: embedding1/Adam tensor_name: Variable/Adam_1 tensor_name: embedding0/Adam_1 tensor_name: embedding0/Adam tensor_name: beta2_power tensor_name: embedding2/Adam_1 tensor_name: embedding0 tensor_name: softmax_w/Adam tensor_name: beta1_power tensor_name: embedding1/Adam_1 tensor_name: embedding1 tensor_name: embedding3/Adam tensor_name: Variable/Adam tensor_name: softmax_b/Adam_1 tensor_name: Variable 这些哪个是权重矩阵值。embedding0,embedding1,embedding2,embedding3的值应该是sku的embedding、brand、cate和shop的embedding吧

你好，这个您是怎么得到的？方便求一份这个代码么？

**Comment by zaibian** [comment]
> 是的

那个是attention权重的值？
