### ISSUE TITLE
关于您代码中的session截断的问题

### ISSUE THREAD

**Issue by ColaXww** [wangzhegeek/EGES#3]
大佬您好，万分感谢您的分享！！！
您在readme中有说：“session截断依据为最后一个action为下单，或者30分钟内没有action”
请问为什么把'下单'操作作为截断的依据呢，如果我在半个小时内，先后下单了A，B两件商品，这不也说A，B之间有潜在的推荐关系吗？

**Comment by wangzhegeek** [comment]
这个根据具体的业务定吧，一般在电商里面已经购买说明这次购物行为就结束了，半小时内下单两个商品可以算作两个session，没什么影响

**Comment by ColaXww** [comment]
哦哦 好的  我明白了  谢谢您的回复！！！
