### ISSUE TITLE
alias table生成方式有问题

### ISSUE THREAD

**Issue by bound2020** [wangzhegeek/EGES#8]
https://github.com/wangzhegeek/EGES/blob/f600b2e4bb293761a0b3f23a1d6ffd0e794f3afd/walker.py#L130
这代码对每个weight都进行了归一化，也就是所有weight都会小等于1。而在alias.py里面，small放的是小于1的数，large放的大于1的数，归一化之后的数都只会放到small中了，那这个alias采样就没有意义了

**Comment by tsotfsk** [comment]
是的，我也遇到了这个问题。貌似只需要在概率归一化那里乘以列表的长度就可以了。

**Comment by lvhao13051830033** [comment]
> https://github.com/wangzhegeek/EGES/blob/f600b2e4bb293761a0b3f23a1d6ffd0e794f3afd/walker.py#L130
> 
> 
> 这代码对每个weight都进行了归一化，也就是所有weight都会小等于1。而在alias.py里面，small放的是小于1的数，large放的大于1的数，归一化之后的数都只会放到small中了，那这个alias采样就没有意义了

相比原算法，少了一句area_ratio_ = np.array(area_ratio) * l，l是neighbors的个数，也就是一个传的概率，一个传的期望。所以这里采样确实没有意义了。
